name: cluster
description: "School Management App."
publish_to: "none"
version: 1.0.0+1

environment:
  # sdk: ^3.9.2
  sdk: '>=3.0.0 <4.0.0'

name: cluster_app
description: A Flutter application for team collaboration

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  web_socket_channel: ^2.2.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.5+3
  file_picker: ^4.6.1
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
flutter:
  uses-material-design: true

