name: cluster
description: "School Management App."
publish_to: "none"
version: 1.0.0+1

environment:
  # sdk: ^3.9.2
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path: ^1.8.3
  intl: ^0.18.1
  file_picker: ^5.5.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/images/ # Папка с изображениями
    # - assets/icons/ # Иконки
    # - assets/data/ # Локальные JSON-файлы (если нужны)
  fonts:
    - family: SomeFont # Кастомные шрифты (если используются)
      fonts:
        - asset: assets/fonts/SomeFont-Regular.ttf
